### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by Klaudioz** [zulufoxtrot/kia-hyundai-tracker#1]
Hi, does the repo work for the US?

I'm getting:

```
self.token: Token = self.api.login(self.username, self.password)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../tests/kia-hyundai-tracker/env/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 247, in login
    raise AuthenticationError("Login Failed")
hyundai_kia_connect_api.exceptions.AuthenticationError: Login Failed
```

**Comment by zulufoxtrot** [comment]
Hi!
This project only supports the EU.
However, it was built using a library that has US support.
So it should be pretty easy to adapt.
In `VehicleClient`, line 55, try changing `region` from 1 to 3, set your credentials and see what happens.
The API is probably different so some features may need to be removed/adapted.

**Comment by Klaudioz** [comment]
Thanks for your answer. Changing the region to `3`, I got immediately this error:

`requests.exceptions.SSLError: HTTPSConnectionPool(host='api.owners.kia.com', port=443): Max retries exceeded with url: /apigw/v1/prof/authUser (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1006)')))`

**Comment by zulufoxtrot** [comment]
Mmmh... sounds like an issue with a lower level library. What version python and `requests` are you on?

**Comment by Klaudioz** [comment]
python3.11.5
requests 2.31.0

**Comment by zulufoxtrot** [comment]
Your system is up to date. Sounds like it's Kia's US server that is using somewhat outdated security. https://github.com/psf/requests/issues/4775

I can't help you with this, maybe open an issue on https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api (the base library for this project).
